name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Run go fmt
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files need formatting:"
          gofmt -s -l .
          exit 1
        fi
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run tests
      run: go test -race -v ./...
    
    - name: Build binary
      run: go build -v -o lazytodo .
    
    - name: Test binary
      run: |
        ./lazytodo --version
        ./lazytodo --help

  build-cross-platform:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Build for multiple platforms
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -o lazytodo-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o lazytodo-linux-arm64 .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -o lazytodo-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o lazytodo-darwin-arm64 .
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -o lazytodo-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -o lazytodo-windows-arm64.exe .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lazytodo-binaries
        path: lazytodo-*